import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — Content Bite',
  description: 'Terms of Service for Content Bite',
}

const LAST_UPDATED = 'April 3, 2026'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-950">
      {/* Nav */}
      <nav className="border-b border-gray-100 dark:border-gray-800 px-4">
        <div className="max-w-3xl mx-auto h-14 flex items-center justify-between">
          <Link href="/" className="text-lg font-bold text-indigo-600">Content Bite</Link>
          <Link href="/login" className="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors">
            Sign in
          </Link>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-50 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 dark:text-gray-500 mb-12">Last updated: {LAST_UPDATED}</p>

        <div className="prose prose-gray dark:prose-invert max-w-none space-y-10 text-sm leading-relaxed text-gray-700 dark:text-gray-300">

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">1. Agreement to Terms</h2>
            <p>
              By accessing or using Content Bite ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. These terms apply to all visitors, users, and others who access the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">2. Description of Service</h2>
            <p>
              Content Bite is an AI-powered news aggregation and briefing service available at <strong>dailycontentbite.com</strong>. The Service allows users to select topics of interest and receive AI-curated news summaries delivered via email. The Service is currently provided free of charge.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">3. User Accounts</h2>
            <p>To use the Service, you must create an account. You agree to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Provide accurate and complete information when registering</li>
              <li>Keep your password secure and confidential</li>
              <li>Notify us immediately of any unauthorized use of your account</li>
              <li>Be responsible for all activity that occurs under your account</li>
            </ul>
            <p>
              You must be at least 13 years of age to use the Service. By creating an account, you represent that you meet this requirement.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">4. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Violate any applicable laws or regulations</li>
              <li>Transmit any harmful, offensive, or disruptive content</li>
              <li>Attempt to gain unauthorized access to any part of the Service</li>
              <li>Scrape, crawl, or extract data from the Service without permission</li>
              <li>Impersonate any person or entity</li>
              <li>Interfere with or disrupt the integrity or performance of the Service</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">5. Content and Intellectual Property</h2>
            <p>
              News articles and content displayed through the Service are sourced from third-party publishers and news sources. Content Bite does not claim ownership of third-party content. All article summaries generated by AI are provided for informational purposes only.
            </p>
            <p>
              The Content Bite name, logo, and original content on the Service are the intellectual property of Ehsan Tarighat and may not be used without prior written permission.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">6. Third-Party Services</h2>
            <p>
              The Service uses third-party services including but not limited to Supabase (database and authentication), Anthropic Claude (AI summaries), and news APIs. Your use of the Service is also subject to the terms and privacy policies of these third-party providers. We are not responsible for the content, privacy practices, or terms of any third-party services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">7. Email Communications</h2>
            <p>
              By creating an account, you consent to receive email briefings and service-related notifications. You may update your email delivery preferences or unsubscribe at any time from your profile settings. We will not send unsolicited marketing emails.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">8. Disclaimer of Warranties</h2>
            <p>
              The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, error-free, or free of harmful components. News summaries are generated by AI and may contain inaccuracies — they are not a substitute for reading original sources.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">9. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, Ehsan Tarighat shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service, even if we have been advised of the possibility of such damages.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">10. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at any time for violation of these Terms. You may delete your account at any time by contacting us. Upon termination, your right to use the Service will immediately cease.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">11. Changes to Terms</h2>
            <p>
              We may update these Terms of Service from time to time. We will notify users of significant changes by updating the "Last updated" date at the top of this page. Continued use of the Service after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the Republic of Uzbekistan, without regard to its conflict of law provisions.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">13. Contact</h2>
            <p>If you have any questions about these Terms of Service, please contact us at:</p>
            <p>
              <strong>Ehsan Tarighat</strong><br />
              <a href="mailto:ehsantarighat@gmail.com" className="text-indigo-600 dark:text-indigo-400 hover:underline">
                ehsantarighat@gmail.com
              </a><br />
              <a href="https://dailycontentbite.com" className="text-indigo-600 dark:text-indigo-400 hover:underline">
                dailycontentbite.com
              </a>
            </p>
          </section>

        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-gray-100 dark:border-gray-800 py-6 text-center">
        <p className="text-xs text-gray-400">© {new Date().getFullYear()} Content Bite · <Link href="/terms" className="hover:underline">Terms of Service</Link></p>
      </footer>
    </div>
  )
}
